//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAS.CommServer.UA.Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://opcfoundation.org/UA/SDK/Configuration.xsd")]
        public string XmlSDKConfigurationNamespace {
            get {
                return ((string)(this["XmlSDKConfigurationNamespace"]));
            }
            set {
                this["XmlSDKConfigurationNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sdk")]
        public string XmlSDKConfigurationPrefix {
            get {
                return ((string)(this["XmlSDKConfigurationPrefix"]));
            }
            set {
                this["XmlSDKConfigurationPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://opcfoundation.org/UA/2008/02/Types.xsd")]
        public string XmlUATypesNamespace {
            get {
                return ((string)(this["XmlUATypesNamespace"]));
            }
            set {
                this["XmlUATypesNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ua")]
        public string XmlUATypesPrefix {
            get {
                return ((string)(this["XmlUATypesPrefix"]));
            }
            set {
                this["XmlUATypesPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.w3.org/2001/XMLSchema-instance")]
        public string XmlSchemainstanceNamespace {
            get {
                return ((string)(this["XmlSchemainstanceNamespace"]));
            }
            set {
                this["XmlSchemainstanceNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xsi")]
        public string XmlSchemainstancePrefix {
            get {
                return ((string)(this["XmlSchemainstancePrefix"]));
            }
            set {
                this["XmlSchemainstancePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ttp://opcfoundation.org/UA/SDK/COM/Configuration.xsd")]
        public string XmlSdkComNamespace {
            get {
                return ((string)(this["XmlSdkComNamespace"]));
            }
            set {
                this["XmlSdkComNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com")]
        public string XmlSdkComPrefix {
            get {
                return ((string)(this["XmlSdkComPrefix"]));
            }
            set {
                this["XmlSdkComPrefix"] = value;
            }
        }
    }
}
